language: python
python:
  - 3.8

stages:
  - build

install: |
  pip install twine cibuildwheel
  git clone https://gitlab.com/fastjet/fastjet.git
  cd fastjet
  git submodule init
  git submodule update
  autoreconf -i
  cd ..

jobs:
  include:

  ##############################################################################
  # BUILDS
  ##############################################################################

    # build on linux
    - name: Build wheels on Linux and deploy
      dist: bionic
      services: docker
      script: python -m cibuildwheel --output-dir wheelhouse
      after_success: |
        if [ ! -z $TRAVIS_TAG ]; then
          python -m twine upload -r testpypi wheelhouse/*.whl
        fi
      env:
        - CIBW_BUILD="cp27-manylinux_x86_64 cp35-manylinux_x86_64 cp36-manylinux_x86_64 cp37-manylinux_x86_64 cp38-manylinux_x86_64 cp39-manylinux_x86_64"

    # build on mac
    - name: Build wheels on Mac and deploy
      os: osx
      osx_image: xcode12
      language: shell
      script: python -m cibuildwheel --output-dir wheelhouse
      after_success: |
        if [ ! -z $TRAVIS_TAG ]; then
          python -m twine upload -r testpypi wheelhouse/*.whl
        fi
      env:
        - CIBW_BUILD="cp27-macosx_x86_64 cp35-macosx_x86_64 cp36-macosx_x86_64 cp37-macosx_x86_64 cp38-macosx_x86_64 cp39-macosx_x86_64"

env:
  global:
    - TWINE_USERNAME=__token__
    - CIBW_BEFORE_ALL="cd fastjet
                       ./configure --prefix=$(HOME)/fastjet-install --enable-pyext --disable-monolithic --disable-allplugins
                       make install
                       cd .."
    - CIBW_ENVIRONMENT="FASTJET_CONFIG=$(HOME)/fastjet-install/bin/fastjet-config CXXFLAGS=-std=c++14"
    - TRAVIS_TAG=test

branches:
  only:
    - main
